create table "public"."livestream_viewers" (
    "id" bigint generated by default as identity not null,
    "wallet" character varying not null,
    "airdropped" boolean not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."livestream_viewers" enable row level security;


CREATE UNIQUE INDEX livestream_viewers_pkey ON public.livestream_viewers USING btree (id);

CREATE UNIQUE INDEX livestream_viewers_wallet_key ON public.livestream_viewers USING btree (wallet);


alter table "public"."livestream_viewers" add constraint "livestream_viewers_pkey" PRIMARY KEY using index "livestream_viewers_pkey";


alter table "public"."livestream_viewers" add constraint "livestream_viewers_wallet_key" UNIQUE using index "livestream_viewers_wallet_key";

create policy "Enable read access for all users"
on "public"."livestream_viewers"
as permissive
for select
to public
using (true);


create policy "enable evrything using service role"
on "public"."livestream_viewers"
as permissive
for all
to service_role;



